### ISSUE TITLE
gatsby 2.14.3 版本无法使用

### ISSUE THREAD

**Issue by zxhycxq** [sigoden/gatsby-plugin-baidu-tongji#1]
报错信息如下所示：
warn Plugin gatsby-plugin-baidu-tongji is not compatible with your gatsby version 2.14.3 - It requires gatsby@^1.0.0

**Comment by sigoden** [comment]
gatsby-plugin-baidu-tongji@^2.0.0 对应 gatsby@^2, gatsby-plugin-baidu-tongji@^1.0.0 对应 gatsby@^1

**Comment by zxhycxq** [comment]
您好，我是直接安装的，默认应该是最新版吧？如果在后面指定版本号@2.0.0，则提示无对应的版本
`npm ERR! code ETARGET

npm ERR! notarget No matching version found for gatsby-plugin-baidu-tongji@2.0.0

npm ERR! notarget In most cases you or one of your depende`

**Comment by sigoden** [comment]
可以运行 `npm ls gatsby-plugin-baidu-tongji` 打印一下版本信息吗？

**Comment by zxhycxq** [comment]
删除所有包文件二次后重新安装可以了，thanks。
